name: Intégration Continue

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Vérification du pipeline
        run: echo "✅ Le pipeline CI fonctionne avec succès !"
